version: '3'
services:
  barista:
    #command: npm run test:unit  
    command: npm run start
    build: .
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      - backend
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

networks:
  backend:
    driver: bridge
